name: Deploy JupyterLite to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install JupyterLite & extensions
        run: |
          python -m pip install --upgrade pip
          pip install "jupyterlite-core>=0.6,<0.7" \
                      "jupyterlite-pyodide-kernel>=0.6,<0.7" \
                      "jupyter-server>=2.14,<3" \
                      jupyterlab_widgets \
                      ipycanvas

      - name: Build JupyterLite site
        run: |
          jupyter lite build --contents content --output-dir _site

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
